### ISSUE TITLE
Support OpenAi SDK ^1.1.0

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape#420] opened 2023-11-06 22:48 UTC

**Comment by zepef** [comment] 2023-11-07 14:08
Hello,

Supporting v1.1.1 would be much appreciated. I am getting now:

 in OpenAiChatPromptDriver
    api_base: str = field(default=openai.api_base, kw_only=True)
AttributeError: module 'openai' has no attribute 'api_base'. Did you mean: 'api_type'?

I suspect evolution of SDK being the cause for this error.

Best regards,

Pierre-Emmanuel

**Comment by collindutter** [comment] 2023-11-07 16:41
Hi @zepef apologies for this issue, we will be making a release today that locks `openai` at `^0.28` until we finish this issue (soon).

**Comment by zepef** [comment] 2023-11-08 02:38
Hello Collin,

I will try it right away. I am really impressed by griptape which I am using to create a medical chatbot. I will keep you updated.

All the best !

Pierre-Emmanuel
________________________________
De : Collin Dutter ***@***.***>
Envoyé : mardi 7 novembre 2023 19:53
À : griptape-ai/griptape ***@***.***>
Cc : Pierre-Emmanuel FEGA ***@***.***>; Mention ***@***.***>
Objet : Re: [griptape-ai/griptape] Support OpenAi SDK ^1.1.0 (Issue #420)


@zepef<https://github.com/zepef> v0.19.4<https://github.com/griptape-ai/griptape/releases/tag/v0.19.4> has been released which should address this issue.

**Comment by zepef** [comment] 2023-11-08 02:58
Collin,

In fact it is an issue with OpenAI 1.1.1 because I get:

ImportError: cannot import name 'OpenAI' from 'openai' (E:\Users\clt\anaconda3\envs\w2\lib\site-packages\openai\__init__.py)

I guess I'll wait until it is supported by griptape because I coded  STT/TTS for my chatbot using new OpenAI SDK.

Regards,

Pierre-Emmanuel
________________________________
De : Collin Dutter ***@***.***>
Envoyé : mardi 7 novembre 2023 19:53
À : griptape-ai/griptape ***@***.***>
Cc : Pierre-Emmanuel FEGA ***@***.***>; Mention ***@***.***>
Objet : Re: [griptape-ai/griptape] Support OpenAi SDK ^1.1.0 (Issue #420)


@zepef<https://github.com/zepef> v0.19.4<https://github.com/griptape-ai/griptape/releases/tag/v0.19.4> has been released which should address this issue.

**Comment by collindutter** [comment] 2023-11-08 16:33
Hi @zepef thanks for trying Griptape and for the kind words! If you install `0.19.4` it will require `openai` `^0.28`. Once [this PR](https://github.com/griptape-ai/griptape/pull/422) is merged you will be able to use `openai``^1.1.1`. We'll keep you updated!

**Comment by zepef** [comment] 2023-11-09 03:10
Collin,

Thank you so much. I am very excited to check it out!

Best regards,

Pierre-Emmanuel
________________________________
De : Collin Dutter ***@***.***>
Envoyé : mercredi 8 novembre 2023 19:33
À : griptape-ai/griptape ***@***.***>
Cc : Pierre-Emmanuel FEGA ***@***.***>; Mention ***@***.***>
Objet : Re: [griptape-ai/griptape] Support OpenAi SDK ^1.1.0 (Issue #420)


Hi @zepef<https://github.com/zepef> thanks for trying Griptape and for the kind words! If you install 0.19.4 it will require openai ^0.28. Once this PR<https://github.com/griptape-ai/griptape/pull/422> is merged you will be able to use openai``^1.1.1. We'll keep you updated!

**Closed** 2023-11-14 17:35 UTC
Labels: enhancement
