### ISSUE TITLE
create persitable local vector driver

### ISSUE THREAD

**Issue by tarbaig** [griptape-ai/griptape#107] opened 2023-07-14 09:23 UTC
When developing vector embedding based apps recreating the embedding of the knowledge base stored in the local vector store causes unnecessary calls to openai. However switching to another vector store driver increases complexity.

A simple method to serialize the local vector store would be nice.

**Describe the solution you'd like**
Subclassing ```LocalVectorStoreDriver``` and add logic to serialize to e.g. pickle.

**Describe alternatives you've considered**
Using a cloud based Vector store for development or adding a locally running service in compose. Both increase complexity.

**Additional context**
I am happy to develop something simple.

**Comment by derekpai** [comment] 2023-09-28 21:09
We are working on this in the related issue:

Duplicate of https://github.com/griptape-ai/griptape/issues/241

**Closed** 2023-09-28 21:10 UTC
Labels: enhancement
