### ISSUE TITLE
Performance deterioration after upgrading to 0.14.0

### ISSUE THREAD

**Issue by jin167** [griptape-ai/griptape#114] opened 2023-07-19 05:09 UTC
**Describe the bug**
Performance of the KnowledgeBaseClient deteriorated after updating to 0.14.0

**To Reproduce**

1. Run the code below.

```
from griptape.memory.tool import TextToolMemory, BlobToolMemory
from griptape.memory.structure import ConversationMemory, BufferConversationMemory
from griptape.tools import Calculator, WebScraper, FileManager, ToolOutputProcessor, KnowledgeBaseClient
from griptape.structures import Agent
from griptape.rules import Rule, Ruleset
from griptape.loaders import TextLoader, PdfLoader
from griptape.engines import VectorQueryEngine
from griptape.drivers import OpenAiPromptDriver


    prompt_driver = OpenAiPromptDriver(
        temperature=0.1
    )

    text_memory = TextToolMemory()
    
    memory_browser = ToolOutputProcessor(
        input_memory=[text_memory]
    )

    engine = VectorQueryEngine()
    namespace = "memo"
    artifacts = TextLoader().load(
          "Problem:
  Layer-packer Layer head 4-axis drive is stopping due to an overcurrent error on the drive itself. The head is always stopping as it tries to pick up the product from array plate. It stops right on-top of the product, every time. 
  
  Observations:
  In the faulted/stopped position, the product on the extremities of the layer-packer head is fixed tightly against it, possibly causing a collision. The product in the center of the layer-packer head is loose and not held against head tightly. 
  
  Solution:
  Vacuum cups were moved relative to the bottom of the acetal, causing them to protrude by 2mm more. The layer packer pick height was then adjusted by 1.5mm away from the vials. Overall, the clearance between the head and the vials has increased by 1.5mm, and the contact between the suction cups and head has been increased by 0.5mm"
    )
    engine.vector_store_driver.upsert_text_artifacts(
        {namespace: artifacts}
    )

    kbCLient = KnowledgeBaseClient(
        description="Contains problem, obervations, and solution related to the layer-packer."
        "Use it to answer any related questions.",
        query_engine=engine,
        namespace=namespace
    )

    agent = Agent(
        prompt_driver=prompt_driver,
        memory=ConversationMemory(),
        tools=[memory_browser, kbCLient],     
    )

    response = agent.run("what is the problem on layer-packer?")
```
2. Unable to retrieve the answer and griptape doesn't try to call on the KnowledgeBaseClient. 

3. Exact same code used to work perfectly fine on 0.13.0 (e.g., able to successfully state the problem, solution, and observations)

**Expected behavior**
State the problem outlined in the text fed to theTextLoader(). 

**Screenshots**
![image](https://github.com/griptape-ai/griptape/assets/50513176/2a3a270b-3bf7-42bc-94c8-f2fe9a945fa6)

**Comment by jin167** [comment] 2023-07-19 05:35
and this also started happening when I migrated to 0.14.0

As seen below, output is empty when KnowledgeBaseClient is used.

![image](https://github.com/griptape-ai/griptape/assets/50513176/98210730-6c16-4be2-adb4-0b75507b5f3b)

**Comment by mgcollie** [comment] 2023-07-19 19:06
I noticed there were some changes to how memory was handled with the ToolOutputProcessor class, and suspected this might be the cause, so I reverted the changes to the previous implementation but it still wasn't able to find the problem on layer-packer.  Reverting griptape and griptape-tools to the previous versions worked. I'll continue to poke around at this and see what else I can find.

**Comment by vasinov** [comment] 2023-07-19 19:09
@jin167, thanks for reporting those. Currently working on debugging. Already found one actual bug. Additionally, tweaking prompts around memory. Will push an update today.

**Comment by jin167** [comment] 2023-07-19 20:54
Awesome, thank you guys! Been building a demo to sell griptape to my colleagues as i've been really impressed with what i was able to do with this lib out of the box haha.

**Comment by vasinov** [comment] 2023-07-19 23:25
@jin167, I just pushed updates to `griptape` and `griptape-tools` with the bug fixe and multiple tweaks to the base prompt. To streamline things even more, you can also do the following:

- Don't use `TextToolMemory` in this example, since the knowledge base tool will return a short answer, which won't be an issue for the prompt size. Also, Griptape now supports automatic memory for some tool activities, so you don't have to explicitly define it.
- I would make the knowledge base description a bit more detailed. May be something like `This knowledge base contains information about the problem, observations, and solution related to the 'layer-packer.' Always use it to answer all related questions`

Let me know if you experience any further issues and thanks for the kind words about Griptape :)

**Comment by jin167** [comment] 2023-07-20 05:23
I tried using the latest version of the griptape and it looks like the problem with KnowledgeBaseClient getting bypassed has been fixed but this happened when i removed the memory from the tool:

agent = Agent(
        prompt_driver=prompt_driver,
        memory=ConversationMemory(),
        tools=[kbCLient],     
    )

![image](https://github.com/griptape-ai/griptape/assets/50513176/3d17fdc0-2260-487a-9283-6dd6f040232e)

and with the memory, i get the following result:

memory_browser = ToolOutputProcessor()
agent = Agent(
        prompt_driver=prompt_driver,
        memory=ConversationMemory(),
        tools=[memory_browser, kbCLient],     
    )
![image](https://github.com/griptape-ai/griptape/assets/50513176/f2800fcf-44cc-49d8-b6a0-40c960e975d7)

Perhaps I am doing something wrong with the new implementation of the griptape?

**Comment by mgcollie** [comment] 2023-07-20 19:11
https://github.com/griptape-ai/griptape/pull/118

**Comment by mgcollie** [comment] 2023-07-20 20:24
@jin167 the above pull request was merged and fixes your problem you shouldn't have to use `gpt-4`.

**Comment by jin167** [comment] 2023-07-21 04:32
Hey mgcollie, thanks for looking into the issue!

I had a chance to update the griptape this afternoon and i ran into the following issues:

with the tool memory, it says it will return the summary but never does:

memory_browser = ToolOutputProcessor()
agent = Agent(
prompt_driver=prompt_driver,
memory=ConversationMemory(),
tools=[memory_browser, kbCLient],
)

![image](https://github.com/griptape-ai/griptape/assets/50513176/f8ad795e-acfd-455c-9b24-cf14e3af6000)

Also, without memory following happened. It seems to ignore the content of the KnowledgeBaseClient:

agent = Agent(
prompt_driver=prompt_driver,
memory=ConversationMemory(),
tools=[kbCLient],
)

![image](https://github.com/griptape-ai/griptape/assets/50513176/174a87a1-8cb6-49e7-a6c8-a4031ea4dd88)

**Comment by vasinov** [comment] 2023-07-21 23:41
Hey @jin167, do you have access to `gpt-4`? We just updated the OpenAI prompt driver to use it by default, so that Griptape agents can function correctly 100% of the time. `gpt-3.5` issues are ongoing and we are still working on improving Griptape performance with those. One way to temporarily fix it is to disable tool memory in your agent with:
```python
Agent(
    tool_memory=None
)
```
Let me know if any of those resolutions work for you!

**Comment by jin167** [comment] 2023-07-24 01:45
Hi @vasinov, sorry for late response I was away over the weekend.

with the agent tool memory set to none, it started working again:

![image](https://github.com/griptape-ai/griptape/assets/50513176/04240d79-cbcb-4b9d-afa4-50b6d2eaa48c)

 Agent(
    tool_memory=None
)

Although it looks like the issue with agent losing memory is still present:

![image](https://github.com/griptape-ai/griptape/assets/50513176/0b77d9cc-e641-4466-9476-b0e11ecf5ac8)

**Comment by vasinov** [comment] 2023-07-28 21:00
Yep, it's unfortunately still happening with `gpt-3.5-turbo`, https://github.com/griptape-ai/griptape/pull/149 should address it once it's complete.

**Closed** 2023-09-27 17:06 UTC
Labels: bug
