### ISSUE TITLE
TextToolMemory doesn't allow configuration of OpenAI api_key

### ISSUE THREAD

**Issue by ysammy** [griptape-ai/griptape#76] opened 2023-06-22 23:58 UTC
It looks to be creating a default prompt driver that doesn't allow for configuration: https://github.com/griptape-ai/griptape/blob/87b258009ba15362a401fe3b5ef5fdf8d27c85e2/griptape/memory/tool/text_tool_memory.py#L39

**Comment by vasinov** [comment] 2023-06-23 01:07
@ysammy, this particular activity is going to be re-written from scratch and allow for better customization, once we resolve https://github.com/griptape-ai/griptape/issues/33. Right now `summarize_text` doesn't even use the driver as it depends on LlamaIndex.

Which tool were you trying to use memory summarization with?

**Comment by ysammy** [comment] 2023-06-23 02:17
I pasted the example from [this](https://docs.griptape.ai/en/latest/griptape-framework/#build-a-simple-pipeline) section into a notebook. The one difference is setting the prompt driver explicitly with my API key. I went this route because I found that the example wasn't respecting `openai.api_key` or `os.environ["OPENAI_API_KEY"]` when run in a notebook.

```python
# Pipelines represent sequences of tasks.
pipeline = Pipeline(
    memory=ConversationMemory(),
    prompt_driver=OpenAiPromptDriver(
        api_key=OPENAI_API_KEY,
    ),
)
```

The output I get is as follows:
```
[06/22/23 10:07:20] INFO     Task d5904fcd762b4a9aaa9bbe80df5c20aa                                                 
                             Input: Load https://www.griptape.ai, summarize it, and store it in griptape.txt       
[06/22/23 10:07:22] INFO     Subtask c3e97f0ad62741c8b7c849355c1e6883                                              
                             Thought: I can use the WebScraper tool to load the website, then use the              
                             TextToolMemory to store the content, and finally use the summarize activity to        
                             generate a summary. After that, I can use the FileManager tool to save the summary to 
                             a file on disk.                                                                       
                             Action: {"type": "tool", "name": "WebScraper", "activity": "get_content", "input":    
                             {"values": {"url": "https://www.griptape.ai"}}}                                       
[06/22/23 10:07:23] INFO     Subtask c3e97f0ad62741c8b7c849355c1e6883                                              
                             Observation: Output of "WebScraper.get_content" was stored in memory "TextToolMemory" 
                             with the following artifact namespace: bc69a45812dc46fd8a51f07b29aee96a               
[06/22/23 10:07:24] INFO     Subtask fcb16c0d788c4673bacc14aaf3fa5aaf                                              
                             Action: {"type": "memory", "name": "TextToolMemory", "activity": "summarize", "input":
                             {"values": {"artifact_namespace": "bc69a45812dc46fd8a51f07b29aee96a"}}}               
[06/22/23 10:07:31] INFO     Subtask fcb16c0d788c4673bacc14aaf3fa5aaf                                              
                             Observation: error summarizing text: RetryError[<Future at 0x2b74942d0 state=finished 
                             raised AuthenticationError>]                                                          
ERROR:root:PromptDriver.run attempt 0 failed: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
Retrying in 1 seconds
```

Tracing the code to where `error summarizing text` is raised as an exception led me to the issue I referenced. I suspect it is because the `OpenAiPromptDriver` created inline doesn't include my API key.

**Comment by vasinov** [comment] 2023-06-23 23:53
> I went this route because I found that the example wasn't respecting openai.api_key or os.environ["OPENAI_API_KEY"] when run in a notebook.

Does that mean that you tried setting the `OPENAI_API_KEY` env var in the notebook before running the code and it didn't work? If so, can you make sure it was set correctly:

```python
os.environ["OPENAI_API_KEY"] = <your key>
assert os.environ["OPENAI_API_KEY"]
```

If that works but the env var doesn't get picked up by the `openai` lib then there is something weird going on :)

**Comment by ysammy** [comment] 2023-06-26 17:58
Can confirm that the assertion passes and the default `OpenAiPromptDriver` for the pipeline cannot find the key. I have not yet had a chance to debug why this is the case.

**Comment by vasinov** [comment] 2023-06-26 20:35
I figured out what the issue is...

`openai.api_key`, which defaults to `OPENAY_API_KEY`, is loaded during the import. Setting `OPENAI_API_KEY` later doesn't do anything. I pushed a fix for this to `main`. Let me know if it fixes the issue in your notebook.

**Closed by vasinov** 2023-06-26 20:35 UTC

**Comment by ysammy** [comment] 2023-06-26 22:06
I figured it was something like that. Confirmed this works!
