### ISSUE TITLE
Empty output with gpt-3.5-turbo

### ISSUE THREAD

**Issue by SAI-sentinal-ai** [griptape-ai/griptape#417] opened 2023-11-06 01:55 UTC
[X] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**To Reproduce**

Change below to gpt-3.5-turbo and the output value is empty

```
import os
from griptape.tools import WebSearch
from griptape.structures import Agent
from griptape.drivers import OpenAiChatPromptDriver

# Initialize the WebSearch tool with necessary parameters
web_search_tool = WebSearch(
    results_count=5,
    google_api_lang="lang_en",
    google_api_key=os.environ["GOOGLE_API_KEY"],
    google_api_search_id=os.environ["GOOGLE_API_SEARCH_ID"],
    google_api_country="us"
)

# Set up an agent using the WebSearch tool
agent = Agent(
    tools=[web_search_tool],
    prompt_driver=OpenAiChatPromptDriver(
      api_key=os.environ["OPENAI_API_KEY"],
      model="gpt-4",
      max_tokens=2000,
      temperature=0
     )
)

#logger_level=logging.ERROR

# Task: Search the web for a specific query
res = agent.run("Return the height and width of an average grown plant in cm, rounded to the closest 5cm: dianthus picotee mix")

print(res.output.value)
```

MacOS Sonoma 14.0

**Comment by collindutter** [comment] 2023-11-07 00:59
Thanks for the report @SAI-sentinal-ai! I'm able to reproduce on my end, we'll look into this and keep you updated.

**Comment by SAI-sentinal-ai** [comment] 2023-11-07 01:04
FYI playing around with rules on the output, i.e., must return JSON and adjusting the original prompt it works something like 30% of the time. Still not ideal...

**Comment by collindutter** [comment] 2023-11-16 17:29
@SAI-sentinal-ai this seems to be working for me on the latest version of griptape (v0.20.0). The actual quality of the answer can vary a bit (gpt-3.5 limitation), but it is consistently outputting an answer. 

I'm going to close this issue, but please feel free to re-open if your results differ from mine.

```python
import os
from griptape.tools import WebSearch
from griptape.structures import Agent
from griptape.drivers import OpenAiChatPromptDriver

# Initialize the WebSearch tool with necessary parameters
web_search_tool = WebSearch(
    results_count=5,
    google_api_lang="lang_en",
    google_api_key=os.environ["GOOGLE_API_KEY"],
    google_api_search_id=os.environ["GOOGLE_API_SEARCH_ID"],
    google_api_country="us",
    off_prompt=False,
)

# Set up an agent using the WebSearch tool
agent = Agent(
    tools=[web_search_tool],
    prompt_driver=OpenAiChatPromptDriver(
        api_key=os.environ["OPENAI_API_KEY"], model="gpt-3.5-turbo-16k"
    ),
)

# Task: Search the web for a specific query
res = agent.run(
    "Return the height and width of an average grown plant in cm, rounded to the closest 5cm: dianthus picotee mix"
)

print(res.output_task.output.value)
```

**Closed by collindutter** 2023-11-16 17:29 UTC
Labels: bug
